spring:
    config:
        import: optional:file:.env[.properties]

    datasource:
        url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        hikari:
            max-lifetime: 600000
    jpa:
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQL92Dialect"
